<?php
include("body-navbar.html");
include("body-hero.html");
include("body-conversation.html");
include("body-hosters2.html");
include("body-location.html");
include("body-request.html");
include("body-partners.html");
include("body-footer.html");
?>